---
title: "Comparison of Repair and Replacement in patients with Active Infective Endocarditis in Native Mitral Valve"
author: "Sun Kim"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = F,
	message = FALSE,
	comment = NA
)
```

# Initialize

```{r initialize, warning=FALSE}
source('R_script/01_Load_Excel.R')
source('R_script/02_Rendering_and_Inclusion.R')
source('R_script/03_Make_anal_data.R')
MV_cut<-0.05
MV_trace=F
PSM_show=T

```

```{r acute, results='asis'}
#acute_data<-anal_data%>%
#  filter(Duration_Onset2Op<=14)

#tbl_data<-acute_data
#source('R_script/04_Make_Tables.R')
#acute_table1<-baseline_tbl
#myt_output='HTML'
#acute_table1%>%print_mytable()

#surv_data<-acute_data
#source('R_script/05_Analysis.R')
#fig5<-surv_fig1
#fig6<-surv_fig2
#fig5
#fig6
```

------------------------------------------------------------------------

# Active IE

## Study population

```{r flowchart}
source("R_script/00_Flowchart.R")
grViz(flowchart)
```

# Prematch

## Tables

```{r pre_match, results='asis'}
tbl_data<-anal_data
source('R_script/04_Make_Tables.R')
table1<-baseline_tbl
SMD1<-smd_table
surv_data<-anal_data
source('R_script/05_Analysis.R')
fig1<-surv_fig1
fig2<-surv_fig2
s_tbl1<-surv_tbl1
s_tbl2<-surv_tbl2
myt_output='HTML'
```

### Repair vs. Replacement

#### Baseline Table

```{r, results='asis'}
table1%>%print_mytable()
```

#### SMD Table

```{r, results='asis'}
SMD1%>%kable()%>%
          kable_styling()
```

### MVR - Tissue vs. Mechanical

```{r, results='asis'}
MVR_tbl%>%print_mytable()
```

### Microorganisms in Active IE

```{r, results='asis'}
org_tbl
```

## Figures

### Survival - Repair vs. Replacment

Median follow up duration : `r Get_median_fu(surv_data$S_TS)` months

```{r, results='asis'}
fig1
s_tbl1%>%
  knitr::kable(format = 'pipe')%>%print()
```

### Composite Endpoint - Repair vs. Replacement

Median follow up duration : `r Get_median_fu(surv_data$C_TS)` months

```{r, results='asis'}
fig2
s_tbl2%>%
  knitr::kable(format = 'pipe')%>%print()
```

# Cox Regression

## Cox - Survival

### Univaiable

Univariable analysis:

```{r Surv_UV_Cox, results='asis'}
#cox_data<-anal_data

source('R_script/06_Cox_functions.R')
#Cox_var<-setdiff(raw_Cox_var,c('Duration_Onset2Op','Lab_BL211103'))
#Cox_var<-c(raw_Cox_var,'Duration_Onset2Op')
Cox_var<-raw_Cox_var

Surv_UV<-anal_data%>%
  select(S_TS,all_of(Cox_var))%>%
  UV_Cox('S_TS')
Surv_UV$result%>%knitr::kable(format = 'pipe')%>%print()


```

#### Significant (p<0.05) variables:

```{r, results='asis'}
Surv_UV$df%>%
  filter(pval<0.05)%>%
  mutate_if(is.numeric,~round(.x,digits=3))%>%
  knitr::kable(format = 'pipe')%>%print()
```

### Multivariable

#### MV candidate (p<`r MV_cut`) variables:

```{r, results='asis'}
MV_candi<-Surv_UV$df%>%
  filter(pval<MV_cut)%>%.$Var
Surv_UV$df%>%
  filter(pval<MV_cut)%>%
  mutate_if(is.numeric,~round(.x,digits=3))%>%
  knitr::kable(format = 'pipe')%>%print()
```

#### Multivariable Cox analysis:

```{r Surv_MV_Cox, results='asis'}
Surv_MV<-anal_data%>%
  select(S_TS,all_of(MV_candi))%>%
  MV_Cox('S_TS',trace=MV_trace,rename=T,keep_variable = 'Mitral_Repair')
```

#### Output

```{r, results='asis'}
Surv_MV$MV_forest
extractHR(Surv_MV$ren_MV_model)%>%knitr::kable(format = 'pipe')%>%print()
Surv_MV$ren_MV_forest
ggadjustedcurves(Surv_MV$MV_model,data=Surv_MV$MV_data,variable='Mitral_Repair',legend.title='',legend.labs = c('Replacement','Repair'),method='conditional')
my_ggadjKM(Surv_MV$MV_model,data=Surv_MV$MV_data,variable='Mitral_Repair',
           leg_lab=c('Replacement','Repair'),ylab='Survival probability')

```

## Cox - Composite end-point
### Univaiable

Univariable analysis:

```{r Composite_UV_Cox, results='asis'}

Composite_UV<-anal_data%>%
  select(C_TS,all_of(Cox_var))%>%
  UV_Cox('C_TS')
Composite_UV$result%>%knitr::kable(format = 'pipe')%>%print()
```

#### Significant (p\<0.05) variables:

```{r, results='asis'}
Composite_UV$df%>%
  filter(pval<0.05)%>%
  mutate_if(is.numeric,~round(.x,digits=3))%>%
  knitr::kable(format = 'pipe')%>%print()
```

### Multivariable

#### MV candidate (p<`r MV_cut`) variables:

```{r, results='asis'}
MV_candi<-Composite_UV$df%>%
  filter(pval<MV_cut)%>%.$Var
Composite_UV$df%>%
  filter(pval<MV_cut)%>%
  mutate_if(is.numeric,~round(.x,digits=3))%>%
  knitr::kable(format = 'pipe')%>%print()
```

#### Multivariable Cox analysis:

```{r Composite_MV_Cox, results='asis'}

Composite_MV<-anal_data%>%
  select(C_TS,all_of(MV_candi))%>%
  MV_Cox('C_TS',trace=MV_trace,rename=T,keep_variable = 'Mitral_Repair')
```

#### Output

```{r, results='asis'}
extractHR(Composite_MV$MV_model)%>%knitr::kable(format = 'pipe')%>%print()
Composite_MV$MV_forest

extractHR(Composite_MV$ren_MV_model)%>%knitr::kable(format = 'pipe')%>%print()
Composite_MV$ren_MV_forest

ggadjustedcurves(Composite_MV$MV_model,data=Composite_MV$MV_data,variable='Mitral_Repair',legend.title='',legend.labs = c('Replacement','Repair'),method='conditional')
my_ggadjKM(Composite_MV$MV_model,data=Composite_MV$MV_data,variable='Mitral_Repair',
           leg_lab=c('Replacement','Repair'),ylab='Freedom from Composite Endpoint')
```

------------------------------------------------------------------------

# PSM

```{r PSM}
source('R_script/08_PSM.R')
print(mat_bal)
```

## Matching balance

```{r PSM_balance, results='asis',eval=PSM_show}
mat_tbl1
mat_tbl2
mat_fig1
mat_fig2
```

## Tables

```{r post_match, results='asis'}
tbl_data<-mat_data
source('R_script/04_Make_Tables.R')
table2<-baseline_tbl
SMD2<-smd_table
myt_output='HTML'
surv_data<-mat_data
source('R_script/05_Analysis.R')
fig3<-surv_fig1
fig4<-surv_fig2
s_tbl3<-surv_tbl1
s_tbl4<-surv_tbl2
```

### Repair vs. Replacement

#### Baseline Table

```{r, results='asis'}
table2%>%print_mytable()
```

#### SMD Table

```{r, results='asis'}


SMD2%>%kable()%>%
          kable_styling()
#org_tbl
```

## Figures

### Survival - Repair vs. Replacement

Median follow up duration : `r Get_median_fu(surv_data$S_TS)` months

```{r, results='asis'}
fig3
s_tbl3%>%
  knitr::kable(format = 'pipe')%>%print()
```

### Composite Endpoint - Repair vs. Replacment

Median follow up duration : `r Get_median_fu(surv_data$C_TS)` months

```{r, results='asis'}
fig4
s_tbl4%>%
  knitr::kable(format = 'pipe')%>%print()
```
